<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>foldingStartMarker</key>
	<string>/\*\*|\{\s*$</string>
	<key>foldingStopMarker</key>
	<string>\*\*/|^\s*\}</string>
	<key>name</key>
	<string>CSS Selectors</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#source_css_selectors</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>source_css_selectors</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>(?ix)
						 \[\s*\]
						|[\.#](?![a-z])
					</string>
					<key>name</key>
					<string>invalid.illegal.css</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>This is totally useless as far as i can tell, but here it is anyway!</string>
					<key>disabled</key>
					<integer>1</integer>
					<key>match</key>
					<string>(?i)(?&lt;=[\w\)\]])\s+(?=[a-z\*\|\[\.\#\:])</string>
					<key>name</key>
					<string>meta.selector.descendant.css</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.control.directive.css</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.separator.array.selectors.css</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(?ix)
						(?&lt;=[\w\)\]])
							 (\s* [\&gt;\+~] \s*)
							|(\s* ,       \s*)
						(?=$|[a-z\*\|\[\.\#\:])</string>
				</dict>
				<dict>
					<key>disabled</key>
					<integer>1</integer>
					<key>match</key>
					<string>(?i)(?&lt;=[\w\)\]])\s*(,)\s*(?=[a-z\*\|\[\.\#\:])</string>
					<key>name</key>
					<string>punctuation.separator.array.selectors.css</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#source_css_selectors-namespace</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\*</string>
					<key>name</key>
					<string>entity.name.tag.wildcard.css</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?i)\b(a|abbr|acronym|address|area|b|base|big|blockquote|body|br|button|caption|cite|code|col|colgroup|dd|del|dfn|div|dl|dt|em|fieldset|form|frame|frameset|(h[1-6])|head|hr|html|i|iframe|img|input|ins|kbd|label|legend|li|link|map|meta|noframes|noscript|object|ol|optgroup|option|p|param|pre|q|samp|script|select|small|span|strike|strong|style|sub|sup|table|tbody|td|textarea|tfoot|th|thead|title|tr|tt|ul|var)\b</string>
					<key>name</key>
					<string>entity.name.tag.css</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>meta.invalid.vendor.microsoft.trident.5</string>
						</dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>entity.other.attribute-name.class.css</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(\.[a-zA-Z][a-zA-Z0-9_-]*)(?=\.)</string>
					<key>name</key>
					<string>entity.other.attribute-name.class.multiple.css</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.entity.css</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(\.)[a-zA-Z][a-zA-Z0-9_-]*</string>
					<key>name</key>
					<string>entity.other.attribute-name.class.css</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.entity.css</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(\.)[a-zA-Z][a-zA-Z0-9_-]*</string>
					<key>name</key>
					<string>entity.other.attribute-name.class.css</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.entity.css</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(?i)(#)[a-z][a-z0-9_-]*</string>
					<key>name</key>
					<string>entity.other.attribute-name.id.css</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.entity.css</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(?i)(:+)\b(after|before|first-child|first-letter|first-line|selection)\b</string>
					<key>name</key>
					<string>entity.other.attribute-name.pseudo-element.css</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.entity.css</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(?i)(:+)\b(root|last-child|first-of-type|last-of-type|only-child|only-of-type|empty|target|disabled|enabled|checked)\b</string>
					<key>name</key>
					<string>entity.other.attribute-name.pseudo-element.css.3</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.entity.css</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(?x)(?i)(:+)
					(-atsc   -[-a-z]+
					|-ms     -[-a-z]+
					|mso     -[-a-z]+
					|-moz    -[-a-z]+
					|-o      -[-a-z]+
					|-wap    -[-a-z]+
					|-webkit -[-a-z]+
					)\b</string>
					<key>name</key>
					<string>entity.other.attribute-name.pseudo-element.css.proprietary</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>(?i)(:+)\b(?:nth-child|nth-last-child|nth-of-type|nth-last-of-type)\b(\()</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.entity.css</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.arguments.begin.css</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(?i)\s*(?=&lt;/style)|(\))</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.arguments.end.css</string>
						</dict>
					</dict>
					<key>name</key>
					<string>entity.other.attribute-name.pseudo-element.css.3</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>\b(even|odd)\b</string>
							<key>name</key>
							<string>constant.language.css</string>
						</dict>
						<dict>
							<key>match</key>
							<string>(\+|-)</string>
							<key>name</key>
							<string>keyword.operator.arithmetic.css</string>
						</dict>
						<dict>
							<key>match</key>
							<string>[0-9]+(\.[0-9]+)?</string>
							<key>name</key>
							<string>constant.numeric.css</string>
						</dict>
						<dict>
							<key>match</key>
							<string>\bn\b</string>
							<key>name</key>
							<string>keyword.other.css</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>(?i)(:+)\blang\b(\()</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.entity.css</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.arguments.begin.css</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(?i)\s*(?=&lt;/style)|(\))</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.arguments.end.css</string>
						</dict>
					</dict>
					<key>name</key>
					<string>entity.other.attribute-name.pseudo-element.css.2</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>[\w-]+</string>
							<key>name</key>
							<string>string.unquoted.language.css</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>(?i)(:+)\b(not)\b(\()</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.entity.css</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.logical.css</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.arguments.begin.css</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(?i)\s*(?=&lt;/style)|(\))</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.arguments.end.css</string>
						</dict>
					</dict>
					<key>name</key>
					<string>entity.other.attribute-name.pseudo-element.css.3</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#source_css_selectors</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.entity.css</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(?i)(:)\b(active|hover|link|visited|focus)\b</string>
					<key>name</key>
					<string>entity.other.attribute-name.pseudo-class.css</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.entity.css</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(?i)(:)\b(([a-z][-a-z]*)?\s?)\b</string>
					<key>name</key>
					<string>entity.other.attribute-name.pseudo-class.unknown.css</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>invalid.illegal.pseudo-class.css</string>
						</dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.entity.css</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(?i)(:)(\s?)</string>
					<key>name</key>
					<string>entity.other.attribute-name.pseudo-class.unknown.css</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>(\[)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.entity.begin.css</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>http://www.w3.org/TR/css3-selectors/#attribute-selectors</string>
					<key>end</key>
					<string>(?i)\s*(?=&lt;/style)|(\]|(?&lt;!\\)\n)</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.entity.end.css</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.attribute-selector.css</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#source_css_selectors-namespace</string>
						</dict>
						<dict>
							<key>match</key>
							<string>(?i)(?&lt;=[\[\|])[a-z][a-z0-9_-]*\b</string>
							<key>name</key>
							<string>entity.other.attribute-name.attribute.css</string>
						</dict>
						<dict>
							<key>match</key>
							<string>\|=</string>
							<key>name</key>
							<string>keyword.operator.comparison.other.css</string>
						</dict>
						<dict>
							<key>match</key>
							<string>~=</string>
							<key>name</key>
							<string>keyword.operator.comparison.contains.delimited.space.css</string>
						</dict>
						<dict>
							<key>match</key>
							<string>\^=</string>
							<key>name</key>
							<string>keyword.operator.comparison.begins.css</string>
						</dict>
						<dict>
							<key>match</key>
							<string>\$=</string>
							<key>name</key>
							<string>keyword.operator.comparison.ends.css</string>
						</dict>
						<dict>
							<key>match</key>
							<string>\*=</string>
							<key>name</key>
							<string>keyword.operator.comparison.contains.css</string>
						</dict>
						<dict>
							<key>match</key>
							<string>=</string>
							<key>name</key>
							<string>keyword.operator.comparison.equal.css</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#string-double</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#string-single</string>
						</dict>
						<dict>
							<key>match</key>
							<string>(?i)(?&lt;==).*?(?=\])</string>
							<key>name</key>
							<string>string.unquoted.attribute-value.css</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>source_css_selectors-namespace</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>entity.name.section.namespace.css</string>
						</dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.parameters.css</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(?i)(?&lt;=(?:^|\s|\[))[a-z][-_\w]*(\|)(?!=)</string>
					<key>name</key>
					<string>meta.namespace-selector.css</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>entity.name.section.namespace.wildcard.css</string>
						</dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.parameters.css</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(?&lt;=(?:^|\s|\[|\(|\}))\*?(\|(?!=))</string>
					<key>name</key>
					<string>meta.namespace-selector.css</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.css.selectors</string>
	<key>uuid</key>
	<string>1C67E107-8F62-4FE4-8D90-8F500C253B8C</string>
</dict>
</plist>
